import { Manrope,DM_Serif_Display } from "next/font/google";
import "./globals.css";
import { CartProvider } from "@/context/CartContext";
import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/Foot.jsx";
import ButtonWsp from "@/components/ButtonWsp/ButtonWsp";
import Faq from "@/components/Faq/Faq";

const manrope = Manrope({
  weight: ["200", "300", "400", "500", "600", "700", "800"],
  subsets: ["latin"],
});

const dm = DM_Serif_Display({
  weight: "400",
  subsets: ["latin"],
});

export const metadata = {
  title: "Casa de Eventos Gaby",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.svg",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="es" suppressHydrationWarning>
      <body className={`${manrope.className} ${dm.className}`} suppressHydrationWarning>
        <ButtonWsp />
        <CartProvider>
          <header>
            <Navbar />
          </header>

          {children}

          <Faq />

          <Footer />
        </CartProvider>
      </body>
    </html>
  );
}
